apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-agent-config
  namespace: {{ $.Release.Namespace }}
data:
  agent_config: |
    agent {
    }
    
    plugins {
    }
    {{ if ne (((.Values.agent).healthChecks).enable) false }}
    health_checks {
      listener_enabled = true
    }
    {{- end }}
